src/components/Footer/Footer.js
src/components/Page/FooterTesting.js

Adding Footer

---

package.json
src/components/ui/ButtonRow/index.js
src/components/ui/ContentBlock/ContentBlock.js
src/styles.css
yarn.lock

- Restyled Header and Body text in "Welcome Section"
- Secondary Button Link color changed to white

[CFDP-175] Updated Welcome Section

---

package.json
src/components/Page/DefaultPage.js
src/components/Page/UITesting.js
src/components/Page/__tests__/DefaultPage.test.js
src/components/features/CampusSelect/__tests__/CampusSelect.tests.js
src/components/features/CampusSelect/index.js
src/components/features/CampusSelect/queries.js
src/components/features/__tests__/features.tests.js
src/components/features/index.js
src/queries/getWebPageBlockItems.js
src/styles.css
yarn.lock

CC: [CFDP-189]
[CFDP-189]: https://christfellowshipchurch.atlassian.net/browse/CFDP-189

Cfdp 186 location finder

---

src/components/ui/ButtonRow/index.js
src/components/ui/ContentBlock/ContentBlock.js
src/queries/getGroupContentItems.js
src/queries/getWebPageBlockItems.js
src/utils.js

Updated the **web-app** to support **openLinkInNewTab** option for all *callsToAction*.

[CFDP-241] New Tab Links

---

src/login/Passcode/index.js
src/login/ResendSMS/index.js

To test this
1. Click Login
2. Type in your phone number
3. Click on the "Didn't get a code?" button
You should get a second confirmation code sent to you

[CFDP-166] Added ability to trigger a new confirmation code to be sent

---

src/articles/ArticleDetail.js
src/browse/Browse.js
src/components/Page/DefaultPage.js
src/components/Page/Login.js
src/components/Page/UITesting.js
src/components/features/EmailCapture/index.js
src/login/Identity/index.js
src/login/Passcode/index.js
src/login/ProfileInformation/index.js
src/login/Reset/PasswordResetForm.js
src/navbar/AuthNavbar/NavbarConnected.js
src/navbar/AuthNavbar/ProfileConnected.js
src/profile/EditProfile.js
src/profile/Profile.js
src/profile/ProfileBanner.js
src/profile/index.js
src/profile/mutations.js
src/profile/profileSelectors.js
src/profile/queries.js
src/router/Profile/index.js
src/router/index.js
src/styles/scss/styles.scss
src/ui/inputs/Checkbox/index.js
src/ui/inputs/TextInput/index.js

Created Profile Page for logged in user
User can ONLY view their profile information

CFDP-345 profile page

---

src/browse/Browse.js
src/browse/CategoryTileFeed/index.js
src/browse/FilterRow/index.js
src/features/EmailCapture/index.js
src/login/Identity/index.js
src/login/Passcode/index.js
src/login/ProfileInformation/index.js
src/login/index.js
src/navbar/AuthNavbar/NavbarConnected.js
src/navbar/AuthNavbar/ProfileConnected.js
src/profile/Profile.js
src/styles/scss/variables.scss
src/ui/Block/index.js
src/ui/HeroSection/index.js
src/ui/cards/ContentCard/index.js
src/ui/cards/FloatingCard/index.js

* Updated **Bootstrap** ``$spacer`` values
* Updated spacing across the site to match **Zeplin** mocks

Spacing Update

---

src/content-single/ContentDetail.js
src/utils.js

* A content article read time is now based off of the word count of the `htmlContent` in an article
* The `readTime` function is located in `utils.js`

[CFDP-387] Article Read Time

---

src/content-feed/CardFeed/index.js
src/content-single/ContentCategories.js
src/content-single/ContentDetail.js

* **Related Content** (articles and events) only shows when *actual content* is available
* **Fixed** content category tags in articles

[CFDP-398] Related Articles/Events Fix

---

src/events/EventDetail.js
src/events/EventSchedule.js
src/router/Events/queries.js

* Added `openLinkInNewTab` ability and *Address* label

[CFDP-340] Events Update

---

src/content-single/ContentDetail.js
src/footer/Footer.js

* For our new **Resources** content channel that uses the **General Content** channel type
* When no author exists, it will hide Author and ReadTime from Content Details page

[CFDP-455] hide author readtime

---

src/content-card-connected/index.js
src/page-builder/Swoop.js
src/router/Events/EventListConnected.js
src/router/Events/queries.js

* Added `hideLabel` attribute to Events

[CFDP-458] hide event card label

---

src/content-card-connected/queries.js
src/content-single/queries.js
src/ui/cards/ContentCard/index.js

[CFDP-478] Removed Icons from Content Card

---

src/home-feed/Features/TileRowCardFeed.js
src/home-feed/index.js
src/home-feed/queries.js

* added `hideLabel` attribute to Feed Features

[CFDP-504] Added hideLabel to Featured Events

---

src/content-single/Author/index.js
src/content-single/UniversalContentItem/index.js
src/navbar/Navbar.js
src/navbar/__tests__/__snapshots__/navbar.test.js.snap
src/navbar/__tests__/navbar.test.js

* FIXED bug where 'X' icon was missing from Navbar toggle on mobile
* Updated tests and snapshots

[CFDP-516] navbar toggle fix

---

src/page-builder/Swoop.js

page builder was not catching unrecognized pages

Fixed 404 Error

---

src/content-single/EventContentItem/EventDetail.js
src/content-single/EventContentItem/EventSchedule.js
src/content-single/EventContentItem/EventShare.js
src/ui/AddToCalendar/index.js
src/ui/AddToCalendar/utils.js

* Updated **EventShare.js**
_added SMS Share button (shows in Mobile view)_
* Updated **AddToCalendar.js**
* Commented out **Address** form EventSchedules and updated the selector to show first Campus in list.
* **_TEMPORARY_** -  added alternative messaging for Share buttons, per request for Easter events. All other events show normal messaging. Would like to find an alternative for managing this in the future.

[CFDP-545] Updated Share Events Card

---

src/redirects.json
src/router/Events/EventConnected.js
src/router/Events/index.js

* Using code from the **RedirectMapper**, added an additional check for redirects for `/events`
* added **ErrorBlock** for unknown events
* updated Easter redirect

Updated Events Router

---

src/content-single/EventContentItem/EventShare.js
src/features-feed/Features/AnnouncementFeed.js
src/features-feed/index.js
src/ui/cards/ContentCard/index.js

* Fixed bottom spacing in smaller cards for the Grid layout in the Home Feed
* Added more spacing between Title and Summary in Content Cards
* Moved Share icons

Home Feed Styling Update

---

package.json
src/login/Identity/index.js
src/login/ProfileInformation/index.js
src/login/Reset/PasswordResetForm.js
src/navbar/AuthNavbar/NavbarConnected.js
src/navbar/AuthNavbar/ProfileConnected.js
src/profile/UserProfile/index.js
src/router/Home/Auth.js
yarn.lock

* Removed all instances to the web-ui-kit from project

[CFDP-569] Removed all instances to the web-ui-kit from project

---

src/footer/Footer.js

[CFDP-588] Update Footer

---

src/content-single/Banner/Share.js
src/content-single/InformationalContentItem/index.js
src/content-single/UniversalContentItem/index.js
src/styles/scss/variables.scss

* Updated Share button component
* Added Share to Informational and Universal Content Item
* Removed caret from dropdowns

Share button update

---

src/router/Events/EventListConnected.js
src/router/Events/queries.js

- Update Events List to pull from order set in Rock, and remove _Featured Events_
- Removed 'Featured Events'
- Removed sorted filters for Events

[CFDP-603] Update Events List

---

src/features/CampusSelect/index.js
src/navbar/Navbar.js
src/ui/Button/Button.js

- Get Directions button in Campus Pages was not doing anything
- Added Google Map link for Get Directions button in the Campus Tiles
- Updated Button.js

[CFDP-620] get directions for campus

---

src/content-card-connected/index.js
src/ui/Icons/Icon.js
src/ui/cards/HighlightCard/index.js

Live highlight card

---

src/login/Reset/PasswordResetForm.js
src/login/Reset/RequestEmailPin.js
src/login/Reset/RequestEmailPinForm.js
src/login/Reset/index.js
src/login/mutations.js
src/router/Login/index.js
src/router/index.sandbox.js
src/ui/Button/Button.js
src/ui/inputs/TextInput/index.js

Reset password

---

src/content-card-connected/index.js
src/content-feed/CardFeed/index.js
src/content-feed/queries.js
src/feature/features/GridFeed.js

- Fixed `hideLabel` in Content Feeds
- updated Live Now label for **ContentCardsConnect**

Fix hide label

---

package.json
src/index.js
yarn.lock

Added the polyfill package with support for ie11  activated
- CFDP-686
- change 1
- change 2

Added react polyfill package

---

src/campus/page-builder.js
src/router/Campuses/index.js

- formatted campus name properly to query campus correctly

Campus Page Bug Fix

---

src/modules/CampusSelect/index.js

- Added services times to show when given on location pages

[CFDP-758] Added Service Times

---

src/browse/Browse.js
src/browse/Search/OtherFeeds.js
src/browse/Search/SearchFeed.js
src/browse/Search/index.js
src/browse/queries.js
src/styles/scss/animations.scss
src/styles/scss/styles.scss
src/ui/cards/TileRowCard/index.js
src/utils.js

- Implemented **Search** bar to **Discover** page
- Added **Search** bar and feed components.
- Updated **TileRowCard** added `loading-bar` and `trimText()`

Added Search to Discover

---

src/navbar/ProfileConnected.js
src/ui/Icons/check-square.js
src/ui/Icons/circle.js
src/ui/Icons/dot-circle.js
src/ui/Icons/index.js
src/ui/Icons/square.js
src/ui/cards/FloatingCard/index.js
src/ui/inputs/Checkbox/index.js
src/ui/inputs/Radio/index.js

- Old FontAwesome css classes were not working for `Checkbox.js` component. 
- Updated Checkbox Icons

Updated Checkbox Icons

---

src/redirects.json

- Added redirect for join-church-online

[CFDP-912] Added redirect for join-church-online

---

src/content-single/EventContentItem/EventLiveLayout.js
src/content-single/EventContentItem/components/CallsToAction.js
src/live/LiveContext.js
src/ui/Icons/arrow-up-right.js
src/ui/Icons/coffee.js
src/ui/Icons/connected.js
src/ui/Icons/gift.js
src/ui/Icons/index.js
src/ui/Media/MediaItem.js
src/ui/cards/CallToActionCard/index.js
src/ui/cards/index.js

Gives a new look to the Call To Action cards by introducing a new card component and a few new icons.
- Load a page that has a live event
- _It should show the new CTA cards and icons_

New CTA Cards

---

src/providers/TheaterModeProvider.js

User should see Theater Mode by default.

Default theater mode to true

---

src/ui/Media/Video.js

- styling on Play Button for video player was altered some how.
- updated play button to correct styling

Fixed styling on Play Button

---

src/App.js

Just trying to trigger a build to load in some new Netlify environment variables.

Triggering build

---

src/ui/GroupBlock/GroupBlock.js

Update GroupBlock.js Fetch Policy

---

src/redirects.json

Type in:
/events/a-christmas-service-for-everyone
And it should end at:
/events/join-us-for-christmas

Redirect old christmas event to new event

---

src/redirects.json

Resolves redirects to point to tune-in-online

---

src/router/LinkTree/index.js
src/router/index.js

**Description**
Create a page in the website called ChristFellowship.Church/info.
Display a list of buttons on the page pulled in from Defined Type
**Definition of Done**
A user is able to navigate to ChristFellowship.Church/info and see a list of buttons in 3 columns on large displays, 2 columns on medium displays, and 1 column on small displays.
Clicking a button should direct out to that link as set in Rock.

[CFDP-1134] Link Tree component and routing

---

src/footer/Footer.js
src/groups/Groups.js

- updated link in `footer` component.

[CFDP-1092] Updated Prayer Link in Footer

---

src/content-single/UniversalContentItem/RelatedContent.js
src/content-single/index.js
src/content-single/queries.js

Patch for failing articles on mobile.

Added missing id's to related articles queries

---

src/router/Home/ExternalHome.js

- Updated url for New Here button on External Marketing home page.

Update ExternalHome button url

---

src/groups/NewGroupContentItemConnected/GroupMember.js
src/groups/NewGroupContentItemConnected/GroupMembers.js
src/groups/index.js
src/groups/index.sandbox.js

* Sandbox file is now live
* Fixed a quick CSS issue for people with long names

[CFDP-1180] Launch groups layout

---

src/groups/NewGroupContentItemConnected/NewGroup.js
src/groups/NewGroupContentItemConnected/index.js
src/ui/cards/RowCard/index.js

Resolves an issue where the parent video for Groups wasn't showing up
Quick patch release from some feedback from Brandi

Shows Parent Video

---

src/redirects.json

removed easter redirect

---

src/groups/Groups.js

Request from the Groups team to update one of the links on the Groups page.

[CFDP-1243] Redirect Requests

---

public/index.html
src/groups/NewGroupContentItemConnected/index.js

Add facebook pixel
